services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./://usr/src/app
      - ./node_modules://usr/src/app/node_modules
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    networks:
      - todo-app-network
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.1-alpine
    hostname: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres-data:/data
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - todo-app-network
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: redis:latest
    networks:
      - todo-app-network
    ports:
      - 6379:6379

volumes:
  postgres-data:

networks:
  todo-app-network:
    driver: bridge
